// Self-owned, bundled public-domain score library.
//
// Replaces the former third-party `musetrainer/library` dependency (no LICENSE,
// mislabeled copyrighted works — see docs/LICENSES/README.md). These scores are
// the app's OWN transcriptions of public-domain compositions, shipped as app
// assets under `public/assets/library/` and generated by
// `scripts/gen-library-scores.mjs`. Benefits:
//   • no runtime dependency on anyone else's repo / CDN — works offline;
//   • the COMPOSITION is PD worldwide (composers long dead) and the ENCODING is
//     authored by us → clean provenance in every jurisdiction;
//   • the "Add a song" UI is unchanged — it consumes entries with a `.url` and
//     imports the clicked one via `addUserSongFromUrl(url)`.
//
// The manifest lists each score; entry URLs point at same-origin bundled assets.

export interface BundledLibraryEntry {
  url: string;
  filename: string;
  label: string;
  composer: string;
  title: string;
  labelJp: string | null;
  composerJp: string | null;
  titleJp: string | null;
  /** Difficulty tier 1–4 (1 初級 … 4 上級); the list is sorted by it. */
  level: number;
  levelJp: string | null;
  icon: string;
  size: number;
}

interface ManifestScore {
  file: string;
  title: string;
  titleJp?: string;
  composer: string;
  composerJp?: string;
  died?: number;
  level?: number;
  levelJp?: string;
  license?: string;
}

interface LibraryManifest {
  version: number;
  scores: ManifestScore[];
}

/** Same-origin base for the bundled catalog. Matches how built-in songs
 *  reference `assets/...` (relative, no leading slash). */
export const LIBRARY_BASE = 'assets/library/';
export const LIBRARY_MANIFEST_URL = LIBRARY_BASE + 'manifest.json';

export interface BundledLibraryDeps {
  fetch: typeof fetch;
  /** Override the asset base (tests). Production: LIBRARY_BASE. */
  base?: string;
}

export interface BundledLibrary {
  /** Read the catalog. First call fetches the bundled manifest; subsequent
   *  calls return the in-memory copy unless `force`. Never hits the network
   *  beyond the same-origin manifest, so it works fully offline. */
  fetchEntries(force?: boolean): Promise<BundledLibraryEntry[]>;
}

function toEntry(s: ManifestScore, base: string): BundledLibraryEntry {
  const label = s.composer && s.title ? s.composer + ' — ' + s.title : s.title || s.file;
  const labelJp = s.composerJp && s.titleJp ? s.composerJp + ' — ' + s.titleJp : s.titleJp || null;
  return {
    url: base + s.file,
    filename: s.file,
    label,
    composer: s.composer || '',
    title: s.title || '',
    labelJp,
    composerJp: s.composerJp || null,
    titleJp: s.titleJp || null,
    level: s.level || 1,
    levelJp: s.levelJp || null,
    icon: '🎼',
    size: 0,
  };
}

export function createBundledLibrary(deps: BundledLibraryDeps): BundledLibrary {
  const base = deps.base ?? LIBRARY_BASE;
  let cache: BundledLibraryEntry[] | null = null;

  async function fetchEntries(force?: boolean): Promise<BundledLibraryEntry[]> {
    if (cache && !force) return cache;
    const res = await deps.fetch(base + 'manifest.json');
    if (!res.ok) throw new Error('library manifest ' + res.status);
    const manifest = (await res.json()) as LibraryManifest;
    const entries = (manifest.scores || [])
      .filter((s) => s && s.file)
      .map((s) => toEntry(s, base))
      // Beginner → advanced, then alphabetical within a tier.
      .sort((a, b) => a.level - b.level || a.label.localeCompare(b.label));
    cache = entries;
    return entries;
  }

  return { fetchEntries };
}
